apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.105.200.208
  environments:
  - key: dev
    owner: praskarn
    repository: demo-jenkinsx
  - key: staging
  - key: production
  ingress:
    domain: 192.168.65.4.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: praskarn
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
