apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        praskarn/demo-jenkinsx: true
        praskarn/firstapp-jx: true
        praskarn/newjxqs: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        praskarn/demo-jenkinsx: merge
        praskarn/firstapp-jx: merge
        praskarn/newjxqs: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - praskarn/demo-jenkinsx
        - praskarn/firstapp-jx
        - praskarn/newjxqs
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - praskarn/demo-jenkinsx
        - praskarn/firstapp-jx
        - praskarn/newjxqs
      target_url: http://lighthouse-jx.127.0.0.1.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
